---
# Example Create git archive from repo
- hosts: all
  become: yes
  tasks:
  - name: Clone a git repo
    git:
      repo: https://github.com/ansible/ansible-examples.git
      dest: /tmp/src/ansible-examples1
      separate_git_dir: /tmp/src/ansible-examples1.git
