---

- hosts: all
  user: root
  become: yes
  
  tasks:
  
  - name: install the latest version of Apache on CentOS
    yum: name=httpd state=latest
    when: ansible_os_family == "RedHat"

  - name: install the latest version of Apache on Debian
    apt: pkg=httpd state=latest 
    when: ansible_os_family == "Debian"

  - name: Start a httpd service
    service: name=httpd state=restarted enabled=yes
