---
- name: Sync Pull task - Executed on  the Destination host "{{groups['demo'][1]}}"
  hosts: "{{groups['demo'][0]}}"
# hosts: demo
  user: ansible
  tasks:   
    - name: Copy the file from managednode1 to managednode2 using Method Pull
      tags: sync-pull
      synchronize:
        src: "{{ item }}"
        dest: "{{ item }}"
        mode: pull
      delegate_to: "{{groups['demo'][1]}}"
      register: syncfile
      run_once: true
      with_items:
       - "/tmp/app01-to-app02.jar"
