---

- hosts: all
  user: root
  become: yes
  vars:
    password: "!"
    user: testa
  tasks:
    - name: add user
      user: name="{{user}}" state=present password="{{password}}" shell=/bin/bash append=yes comment="test User"
                        
    - name: Determine available groups
      getent:
        database: group

    - name: Add additional groups to user
      user: name="{{user}}" groups="{{item}}" append=yes
      when: item in ansible_facts.getent_group
      with_items: 
        - sudo
        - wheel
