---
- hosts: all
  become: yes
  tasks:
  - name: Write some content in a file /tmp/foo.txt
    copy:
      dest: /tmp/foo.txt
      content: "Good Morning!\nAwesome sunshine today."
    register: display_file_content
  - name: Debug display_file_content
    debug:
      var: display_file_content
      verbosity: 2
