---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: Display all variables/facts known for a host
    debug:
      var: "hostvars[inventory_hostname]['ansible_env'].SSH_CONNECTION.split(' ')"
      verbosity: 4
